[2022-03-21 23:14:18,988] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-21 23:14:19,003] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-21 23:14:19,005] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:14:19,006] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:14:19,007] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:14:19,022] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-07-02 06:00:00+00:00
[2022-03-21 23:14:19,030] {standard_task_runner.py:52} INFO - Started process 2192 to run task
[2022-03-21 23:14:19,035] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-07-02T06:00:00+00:00', '--job-id', '573', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp76ose5k2', '--error-file', '/tmp/tmp7kvd11xd']
[2022-03-21 23:14:19,037] {standard_task_runner.py:77} INFO - Job 573: Subtask download_dataset_task
[2022-03-21 23:14:19,123] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:14:19,165] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:14:19,193] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-02T06:00:00+00:00
[2022-03-21 23:14:19,197] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 23:14:19,201] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201907-citibike-tripdata.csv.zip > /opt/***/201907-citibike-tripdata.csv.zip']
[2022-03-21 23:14:19,221] {subprocess.py:85} INFO - Output:
[2022-03-21 23:16:19,588] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-21 23:16:20,025] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190702T060000, start_date=20220321T231418, end_date=20220321T231620
[2022-03-21 23:16:20,275] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 23:16:20,621] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-21 23:32:09,669] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-21 23:32:09,694] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-21 23:32:09,697] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:32:09,699] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:32:09,701] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:32:09,733] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-07-02 06:00:00+00:00
[2022-03-21 23:32:09,749] {standard_task_runner.py:52} INFO - Started process 3232 to run task
[2022-03-21 23:32:09,768] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-07-02T06:00:00+00:00', '--job-id', '623', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp23md8zpj', '--error-file', '/tmp/tmpd0galw5m']
[2022-03-21 23:32:09,771] {standard_task_runner.py:77} INFO - Job 623: Subtask download_dataset_task
[2022-03-21 23:32:09,956] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:32:10,040] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:32:10,079] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-02T06:00:00+00:00
[2022-03-21 23:32:10,082] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 23:32:10,085] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201907-citibike-tripdata.csv.zip > /opt/***/201907-citibike-tripdata.csv.zip']
[2022-03-21 23:32:10,123] {subprocess.py:85} INFO - Output:
[2022-03-21 23:36:10,422] {subprocess.py:89} INFO - curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
[2022-03-21 23:36:10,445] {subprocess.py:93} INFO - Command exited with return code 56
[2022-03-21 23:36:10,567] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-03-21 23:36:10,591] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190702T060000, start_date=20220321T233209, end_date=20220321T233610
[2022-03-21 23:36:10,658] {standard_task_runner.py:92} ERROR - Failed to execute job 623 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-03-21 23:36:10,709] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 23:36:10,794] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-23 09:08:57,137] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-23 09:08:57,147] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-23 09:08:57,148] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:08:57,148] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 09:08:57,149] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:08:57,159] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-07-02 06:00:00+00:00
[2022-03-23 09:08:57,165] {standard_task_runner.py:52} INFO - Started process 1371 to run task
[2022-03-23 09:08:57,169] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-07-02T06:00:00+00:00', '--job-id', '708', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpb4wdakvk', '--error-file', '/tmp/tmpk61vhfgh']
[2022-03-23 09:08:57,170] {standard_task_runner.py:77} INFO - Job 708: Subtask download_dataset_task
[2022-03-23 09:08:57,240] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 09:08:57,288] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 09:08:57,314] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-02T06:00:00+00:00
[2022-03-23 09:08:57,316] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-23 09:08:57,317] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201907-citibike-tripdata.csv.zip > /opt/***/201907-citibike-tripdata.csv.zip']
[2022-03-23 09:08:57,333] {subprocess.py:85} INFO - Output:
[2022-03-23 09:12:53,146] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-23 09:12:53,172] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190702T060000, start_date=20220323T090857, end_date=20220323T091253
[2022-03-23 09:12:53,200] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 09:12:53,267] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 16:10:06,889] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-23 16:10:06,940] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-23 16:10:06,941] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:10:06,942] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 16:10:06,951] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:10:06,963] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-07-02 06:00:00+00:00
[2022-03-23 16:10:06,969] {standard_task_runner.py:52} INFO - Started process 4400 to run task
[2022-03-23 16:10:06,973] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-07-02T06:00:00+00:00', '--job-id', '1016', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpgovtddwy', '--error-file', '/tmp/tmp4_y4pf6u']
[2022-03-23 16:10:06,975] {standard_task_runner.py:77} INFO - Job 1016: Subtask download_dataset_task
[2022-03-23 16:10:07,046] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 16:10:07,101] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 16:10:07,133] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-02T06:00:00+00:00
[2022-03-23 16:10:07,135] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-23 16:10:07,137] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201907-citibike-tripdata.csv.zip > /opt/***/201907-citibike-tripdata.csv.zip']
[2022-03-23 16:10:07,153] {subprocess.py:85} INFO - Output:
[2022-03-23 16:13:52,149] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-23 16:13:52,196] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190702T060000, start_date=20220323T161006, end_date=20220323T161352
[2022-03-23 16:13:52,260] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 16:13:52,305] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 11:02:34,378] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-26 11:02:34,390] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-26 11:02:34,391] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 11:02:34,391] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 11:02:34,392] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 11:02:34,406] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-07-02 06:00:00+00:00
[2022-03-26 11:02:34,414] {standard_task_runner.py:52} INFO - Started process 6763 to run task
[2022-03-26 11:02:34,418] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-07-02T06:00:00+00:00', '--job-id', '1376', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpmok35tkz', '--error-file', '/tmp/tmpab753uwt']
[2022-03-26 11:02:34,420] {standard_task_runner.py:77} INFO - Job 1376: Subtask download_dataset_task
[2022-03-26 11:02:34,494] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 11:02:34,539] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 11:02:34,563] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-02T06:00:00+00:00
[2022-03-26 11:02:34,565] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-26 11:02:34,567] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201907-citibike-tripdata.csv.zip > /opt/***/201907-citibike-tripdata.csv.zip']
[2022-03-26 11:02:34,585] {subprocess.py:85} INFO - Output:
[2022-03-26 11:04:12,106] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-26 11:04:12,147] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190702T060000, start_date=20220326T110234, end_date=20220326T110412
[2022-03-26 11:04:12,199] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 11:04:12,246] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 15:36:47,418] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-26 15:36:47,432] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2022-03-26 15:36:47,433] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:36:47,433] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 15:36:47,434] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:36:47,446] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-07-02 06:00:00+00:00
[2022-03-26 15:36:47,453] {standard_task_runner.py:52} INFO - Started process 20533 to run task
[2022-03-26 15:36:47,457] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2019-07-02T06:00:00+00:00', '--job-id', '1615', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpkn_i1vnj', '--error-file', '/tmp/tmp0vsx5fjp']
[2022-03-26 15:36:47,458] {standard_task_runner.py:77} INFO - Job 1615: Subtask download_dataset_task
[2022-03-26 15:36:47,549] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2019-07-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 15:36:47,597] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 15:36:47,622] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-02T06:00:00+00:00
[2022-03-26 15:36:47,624] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-26 15:36:47,626] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/201907-citibike-tripdata.csv.zip > /opt/***/201907-citibike-tripdata.csv.zip']
[2022-03-26 15:36:47,645] {subprocess.py:85} INFO - Output:
[2022-03-26 15:37:23,218] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-26 15:37:23,265] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20190702T060000, start_date=20220326T153647, end_date=20220326T153723
[2022-03-26 15:37:23,328] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 15:37:23,385] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
